experimentName: 'Template Experiment' &fullName
shortName: 'template' &shortName
apiControllers: # The default export from each of these locations will be attached to a pushkin API
  - mountPath: &shortName
    location: 'api controllers'
worker:
  location: 'worker'
webPage:
  mountPath: &shortName
  location: 'web page'
migrations:
  location: 'migrations'
seeds:
  location: 'seeds'
